version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Pulling build cache...
      - ECR_REPO="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME"
      - docker pull $ECR_REPO:builder || true
      - echo Building the builder stage...
      - |
        docker build \
          --target builder \
          --cache-from $ECR_REPO:builder \
          -t $ECR_REPO:builder .
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - |
        docker build \
          --cache-from $ECR_REPO:builder \
          -t $ECR_REPO:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REPO:builder
      - docker push $ECR_REPO:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE_REPO_NAME $ECR_REPO:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json